config/routes.rb
Rails.application.routes.draw do
  mount PointlessFeedback::Engine, :at => '/feedback'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :packages do
    member do
      get :fetch_detail
    end
  end
  resources :bookings 
  devise_for :users
  authenticated :user do
   get'contact/index' 
    root 'dashboard#index', as: :authenticated_root
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  
  # Associations
  belongs_to :user
  belongs_to :package
  
  # Valdations
  validates :contact, presence: true, length: { minimum: 6, maximum: 10}
  
end

app/models/package.rb
class Package < ApplicationRecord
 has_many :bookings
 has_one_attached :avatar

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user  , :admin ]
  after_initialize :set_default_role, :if => :new_record?
  has_many :bookings  

  def set_default_role
    self.role ||= :user
  end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  

  # if user_signed_in? do
  #   before_action :set_user_role
  # end
    
  # private
  # def set_user_role
  #   if current_user.role == 'admin'
  #     'admin'
  #   elsif current_user.role == 'employee'
  #     'employee'
  #   end
  # end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings.includes(:package)
    

  end

  def show
    
  end

  def new 
    @packages = Package.all
    @booking = Booking.new
  end

  def create
    @booking = current_user.bookings.build(booking_params)

    respond_to do |format|
      if @booking.save
        format.html{redirect_to bookings_path, notice: 'Your Booking is made.'}
        format.json{render :show, status: :created, location: @package}
      else
        format.html{render :new}
        form.json {render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def booking_params
    params.require(:booking).permit(:package_id, :booked_for, :no_of_person, :contact)
  end
  def destroy
    @booking = Booking.find(params[:id])
    if @booking.present?
      @booking.destroy
    end
    redirect_to root_url
end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
  def show
  end  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :authenticate_user!


  def index
    @packages = Package.all
  end
  def edit
    @Package = current_user
  end

end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_package, only: [:show, :edit, :update, :destroy, :fetch_detail]

  # GET /packages
  # GET /packages.json
  def index
    @packages = Package.all
  end

  # GET /packages/1
  # GET /packages/1.json
  def show
  end

  # GET /packages/new
  def new
    @package = Package.new
  end

  # GET /packages/1/edit
  def edit
  end

  # POST /packages
  # POST /packages.json
  def create
    @package = Package.new(package_params)

    respond_to do |format|
      if @package.save
        format.html { redirect_to @package, notice: 'Package was successfully created.' }
        format.json { render :show, status: :created, location: @package }
      else
        format.html { render :new }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packages/1
  # PATCH/PUT /packages/1.json
  def update
    respond_to do |format|
      if @package.update(package_params)
        format.html { redirect_to @package, notice: 'Package was successfully updated.' }
        format.json { render :show, status: :ok, location: @package }
      else
        format.html { render :edit }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packages/1
  # DELETE /packages/1.json
  def destroy
    @package.destroy
    respond_to do |format|
      format.html { redirect_to packages_url, notice: 'Package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fetch_detail
    render json: {
      title: @package.title,
      description: @package.description,
      price: @package.price,
      inclusion: @package.inclusion,
      exclusion: @package.exclusion,
      pickup: @package.pickup,
      avatar: @package.avatar,
    }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package
      @package = Package.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_params
      params.require(:package).permit(:title, :description, :price, :inclusion, :exclusion, :pickup, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def packages_options
    Package.all.map do |package|
      [
        package.title,
        package.id
      ]
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h3 style="text-align: center;"> My Booking</h3>
    <% if user_signed_in? %>
      <h3>Welcome <h4><%= current_user.name %> !!!</h4></h3>
    <%end%>      
    <table class="table table-hover">
        <thead>
          <tr>
          	<th>Package</th>
            <th>Booked For</th>
            <th>No of People</th>
            <th>Status</th>
            

            <th colspan="3"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @bookings.each do |booking| %>
            <tr>
            	<td><%= booking.package.title %>	
              <td><%= booking.booked_for %></td>
              <td><%= booking.no_of_person %></td>
              <%if booking.confirm==true %>
                <td><strong>Confirmed</strong></td>
              <%else%>
                <td><%= link_to 'Cancle Booking', booking, class: 'btn btn-danger',method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <%end%>
            </tr>
          <% end %>
        </tbody>

      <br>

    </table>
   <div style="text-align: center;"> <%= link_to 'New Tour', new_booking_path, class: 'btn btn-primary'  %></div>></td>
     
</div>      

app/views/bookings/new.html.erb
<div class="container">
	<h1 style="text-align: center;">Book Now</h1>

	<%= form_for @booking do |f| %>
		<div class='form-group'>
			<%= f.label :package_id, 'Package', class: 'label-control' %>
		  <%= f.select :package_id, options_for_select(packages_options), {:include_blank => "Select"}, class: 'form-control package-select' %>
	  </div>
	  <div class='package-detail'>
	  </div>
	  <div class="form-group">
	  	<%=f.label :booked_for, 'When', class: 'label-control'%>
	  	<%= f.date_field :booked_for, class: 'form-control' %>
	  </div>
	  <div class="form-group">
	  	<%=f.label :no_of_person, 'Total No of People', class: 'label-control'%>	
	  	<%= f.number_field :no_of_person,:input_html => {:min=>'1' , :max=>10}, class: 'form-control' %>
	  </div>
	  <div class="form-group">
	  	<%=f.label :contact, 'Mobie No', class: 'label-control'%>	
	  	<%= f.number_field :contact, class: 'form-control' %>
	  </div>
	  <input class="form-control" type="text" placeholder="Warning: You cannot update your booking once you booked. Else Contact Us" readonly>


	  <%=f.submit 'Book', class: 'btn btn-primary' %>
	<% end %>
</div>      

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>


<p>Find me in app/views/bookings/show.html.erb</p>

app/views/dashboard/index.html.erb
<!-- Page Content -->
<body>

  <!-- Navigation -->
 <div class="welcom" style="margin-left: 20%;">
    <% if signed_in? %>
      <h4 >Hi</h4><%= current_user.name %>!  
    <%end%>
 </div>
  <!-- Header -->


  <!-- Page Content -->
  <div class="container" style="text-align: center;">
    <div class="Header Text">
      <H2> Welcome to Treak & Tour Nepal </H2>
    </div>
  <div id="slideshow">

   <div>
     <img src="https://trekroute.com/wp-content/uploads/2015/07/Everest-Base-Camp-e1438949700440.jpg" height="400" width="1000" >
   </div>
   <div>
     <img src="https://www.nepalitimes.com/wp-content/uploads/2019/02/rara-1.jpg" height="400" width="1000">
   </div>
   <div>
     <img src="http://images4.fanpop.com/image/photos/23700000/Beautiful-nepal-natrally-nepal-23757405-1280-800.jpg" height="400" width="1000">

   </div>
   <p style="font-size:1vw;">“Be fearless in the pursuit of what sets your soul on fire.” – Jennifer Lee</p>
</div>
       
    <% if signed_in? %>
      <h4>Hi</h4><%= current_user.name %>!  
    <%end%>  

    <!-- /.row -->
    <h3 style="text-align: center;"> List of Packages</h3>

    <div class="row">
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="https://www.oyorooms.com/blog/wp-content/uploads/2018/06/Nepal-Historical-Places-Featured-Image.jpg"
          height="300" width="300" alt="">
          <div class="card-body">
            <h4 class="card-title">Visit Cultural</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus.</p>
          </div>
          <div class="card-footer">
            <div style="text-align: center;"><%= link_to 'Book Packages', new_booking_path, class: 'btn btn-primary '%></div>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="https://media-cdn.tripadvisor.com/media/photo-s/0b/6e/6c/db/natural-beauty-of-nepal.jpg"
          height="300" width="300" alt="">
          <div class="card-body">
            <h4 class="card-title">Beauty of Nature</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus.</p>
          </div>
          <div class="card-footer">
            <div style="text-align: center;"><%= link_to 'Book Packages', new_booking_path, class: 'btn btn-primary '%></div>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="http://www.expeditionsnepal.com/wp-content/uploads/2019/03/himalaya-4039495_1920-1920x1200.jpg"
          height="300" width="300" alt="">
          <div class="card-body">
            <h4 class="card-title">See The Beauty of Mountain</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus.</p>
          </div>
          <div class="card-footer">
            <div style="text-align: center;"><%= link_to 'Book Packages', new_booking_path, class: 'btn btn-primary '%></div>
          </div>
        </div>
      </div>
    </div>
      <div class="col-md-12">
        
        <h2 style="text-align: center;">Visit US</h2>      
        <div class="mapouter"><div class="gmap_canvas"><iframe width="1170" height="333" id="gmap_canvas" src="https://maps.google.com/maps?q=Kathmandu%20thamel&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.crocothemes.net"></a></div><style>.mapouter{position:relative;text-align:right;height:333px;width:1070px;}.gmap_canvas {overflow:hidden;background:none!important;height:333px;width:1070px;}</style></div>
      </div>
      <div style="text-align: center"><%=link_to 'Give Us a FeedBack', pointless_feedback_path, class: 'btn btn-primary' %></div>>
  </div>
<script type="text/javascript">
$("#slideshow > div:gt(0)").hide();

setInterval(function() { 
  $('#slideshow > div:first')
    slideshow.goToPrevSlide();   
} ,30)    
</script> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Main</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'toastr_rails/flash' %>

    <nav class="navbar navbar-inverse header navbar-fixed-top">
      <ul class="nav navbar-nav navbar-left">
        <img style="max-width:100px; margin-top: -40px; margin-left: 40px; padding-top: 5px; padding-bottom: -10px; text-align: center " src="https://i.ibb.co/YfY73QD/d94b5064-998e-485e-9d89-4b266cf38c7e-200x200.png" alt="d94b5064-998e-485e-9d89-4b266cf38c7e-200x200"> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <%if user_signed_in? %>
          <li><%= link_to 'My Booking', bookings_path %></li>
          <li><%= link_to 'My Profile', edit_user_registration_path %>

          <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>

        <%else%>  
          <li><%= link_to '<i class = "glyphicon glyphicon-user"></i> Sign Up'.html_safe, new_user_registration_path%></li>
          <li><%= link_to '<i class = "glyphicon glyphicon-log-in"></i> Sign In'.html_safe, new_user_session_path %></li>
        <%end -%>

      </ul></nav><br>
    </nav> </br>
    <div style="margin-top: 30px;"><%= yield %></div>

<div style="text-align: center"><%=link_to 'Give Us a FeedBack', pointless_feedback_path, class: 'btn btn-primary' %></div>>    
<div class="footer">
  
  <p>© 2019 Copyright!!<a href="https://www.facebook.com/himal.princemalla">Contact Me</a></p>
</div>
<style>
  .header{
    
    width: 100%;
  }
  .footer {
    position: fixed;
  padding-top: 5% 
    top: 98%;
    left: 0;
    bottom: 0;
    width: 100%;
    background-color: black;
    color: white;
  text-align: center;
}
</style>
  </body>
</html>

app/views/pointless_feedback/messages/new.html.erb
    <% if PointlessFeedback.using_captcha? %>
      <head>
        <script src='https://www.google.com/recaptcha/api.js'></script>
      </head>
    <% end %>

    <%= form_for @message do |f| %>
      <% if @message.errors.any? %>
        <div class="error_messages">
          <h2>
            <%= I18n.t('activerecord.errors.header', :default => 'Invalid Fields') %>
          </h2>

          <p>
            <%= I18n.t('activerecord.errors.message', :default => 'Correct the following errors and try again.') %>
          </p>

          <ul>
            <% @message.errors.full_messages.each do |message| %>
              <li><%= message.html_safe %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <fieldset class="user-fields">
        <legend>About You</legend>

        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>

        <div class="field">
          <%= f.label :email_address %>
          <%= f.text_field :email_address %>
        </div>
      </fieldset>

      <fieldset class="feedback-fields">
        <legend>Leave Your Feedback</legend>

        <div class="field">
          <%= f.label :topic %>
          <%= f.select :topic, PointlessFeedback.message_topics, { :prompt => true } %>
        </div>

        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description %>
        </div>

        <!-- This is a honeypot field to keep the spammers away. Do not remove. -->
        <!-- If this field is filled in, feedback will not be emailed -->
        <div class="contact-input" style="position: absolute; left: -9999px;">
          <%= f.text_field :contact_info %>
        </div>
        <!-- End of honeypot field -->

      </fieldset>

      <% if PointlessFeedback.using_captcha? %>
        <div class="g-recaptcha" data-sitekey="<%= PointlessFeedback.google_captcha_site_key %>"></div>
      <% end %>

      <%= f.submit 'Submit' %>
    <% end %>